version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: ap-south-1
    ECR_REPO: 863183417803.dkr.ecr.ap-south-1.amazonaws.com/sam-dev
    IMAGE_TAG: latest

phases:
  install:
    runtime-versions:
      java: corretto17
      docker: 19
    commands:
      - echo Installing dependencies...
      - cd demo
      - mvn clean package -DskipTests
      - cd ..

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPO

  build:
    commands:
      - echo Building Docker image for ECS (amd64 platform)...
      - docker buildx create --use
      - docker buildx build --platform linux/amd64 -t $ECR_REPO:$IMAGE_TAG ./demo

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $ECR_REPO:$IMAGE_TAG
      - echo Creating imagedefinitions.json for ECS deployment...
      - printf '[{"name":"sam-dev","imageUri":"%s"}]' $ECR_REPO:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
      - echo Build completed successfully!

artifacts:
  files:
    - imagedefinitions.json
